import{a as w,S as L,i as a}from"./assets/vendor-Db2TdIkw.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function i(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=i(r);fetch(r.href,o)}})();const S="49410735-a7c42e02d1ae980291a09914d",v="https://pixabay.com/api/",R=15;async function m(t,e=1,i=R){try{const n=await w.get(v,{params:{key:S,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:i}});if(n.status!==200)throw new Error(`Failed to fetch images. Status: ${n.status}`);return n.data}catch(n){throw console.error("Error loading images:",n.message||n),n}}const c=document.querySelector(".gallery"),h=document.querySelector("#load-more"),u=document.querySelector("#loader");let P=new L(".gallery a",{captionData:"alt",captionDelay:250});function $(t){return t.map(e=>`
        <li class="gallery-item">
          <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy"/>
          </a>
          <div class="info">
            <p><b>Likes:</b> ${e.likes}</p>
            <p><b>Views:</b> ${e.views}</p>
            <p><b>Comments:</b> ${e.comments}</p>
            <p><b>Downloads:</b> ${e.downloads}</p>
          </div>
        </li>`).join("")}function y(t){if(!t||t.length===0){g(),a.warning({title:"Oops",message:"No images found",position:"topRight"});return}c.insertAdjacentHTML("beforeend",$(t)),P.refresh()}function g(){c.innerHTML=""}function f(t){h&&(h.style.display=t?"block":"none")}function q(){if(c.firstElementChild){const{height:t}=c.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}}function b(){u&&(u.style.display="block")}function E(){u&&(u.style.display="none")}const M=document.querySelector(".form"),A=document.querySelector("#search-input"),G=document.querySelector("#load-more");let s=1,l="",p=0;const I=15;M.addEventListener("submit",async t=>{if(t.preventDefault(),l=A.value.trim(),!l){a.error({title:"Error",message:"Enter a search query",position:"topRight"});return}g(),s=1,f(!1),b();try{const{hits:e,totalHits:i}=await m(l,s);p=i,y(e),e.length>0&&e.length<p&&f(!0)}catch{a.error({title:"Error",message:"Failed to fetch images. Try again.",position:"topRight"})}finally{E()}});G.addEventListener("click",async()=>{s++,b();try{const{hits:t}=await m(l,s);y(t),q(),s*I>=p&&(f(!1),a.info({title:"End",message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}finally{E()}});
//# sourceMappingURL=index.js.map
